name: py311_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip

  # 머신러닝 라이브러리
  - numpy
  - pandas
  - scikit-learn
  - networkx
  - scipy
  - statsmodels
  - xgboost
  - lightgbm
  - catboost
  - imbalanced-learn

  # 시각화 관련 라이브러리
  - matplotlib
  - seaborn
  - plotly
  - dash
  - pyvis

  # 유틸 및 Jupyter 환경
  - jupyterlab
  - notebook
  - ipykernel
  - nb_conda_kernels
  - tqdm
  - openpyxl
  - pydantic
  - hydra-core
  - mlflow
  - optuna
